default: &default
  adapter: postgresql
  encoding: unicode
  # username: ********
  # password: ********
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: symphony_development

test:
  <<: *default
  database: symphony_test

production:
  <<: *default
  database: symphony_production
  username: symphony
  password: <%= ENV["SYMPHONY_DATABASE_PASSWORD"] %>
